### ISSUE TITLE
Oauth login with facebook and instagram buttons in login modal - frontend.

### ISSUE THREAD

**Issue by leovcunha** [Fairshots/Fairshots.org#23]

**Comment by leovcunha** [comment]
@arunkumar413

**Comment by arunkumar413** [comment]
Using this module (https://www.npmjs.com/package/react-social-login-buttons) as it's easier, simpler to work and customise.

![signin_modal](https://user-images.githubusercontent.com/7776779/59823273-5a666100-934b-11e9-90db-1d68b147b300.png)

**Comment by leovcunha** [comment]
#68
