### ISSUE TITLE
Photographer's Card displaying profile picture twice

### ISSUE THREAD

**Issue by nando-fairshots** [Fairshots/Fairshots.org#74]
## Expected Behavior

Photographer's card should display the photographer's profile picture small on the circle in the bottom left, and first image of the portfolio as the main image.
## Current Behavior

displaying the photographer's profile picture on both spaces
## Steps to Reproduce

1. Log in as an NGO
2. Go to one of your projects
3. Look at the applicant's cards
4.

**Comment by leovcunha** [comment]
This is expected to happen if photographer has no photo in Portfolio. Besides, applicants view was changed from Card view to Table View. So problem solved @nando-fairshots
